### ISSUE TITLE
Yönetim - Önerilen Makaleler Paneli Açıklama Metni

### ISSUE THREAD

**Issue by ileri** [omuoyak/oyak.omu.edu.tr#5]
Yönetim panelinde önerilen makaleler panelinde toplu gösterilen listede açıklama kısmı HTML taglı  haliyle yazdırılıyor. Doğrudan biçimlendirilmiş şekilde gösterilmesi gerekmekte.([Sanitize](https://api.rubyonrails.org/classes/ActionView/Helpers/SanitizeHelper.html#method-i-sanitize))

![Önerilen Makaleler Paneli Açıklama Metni](https://user-images.githubusercontent.com/13015363/57696776-4e0b2c00-765a-11e9-8888-701b54d544dd.png)

**Comment by wemrekurt** [comment]
Bence burada biçimlendirilmiş şekli görünümde problemler oluşturabilir. Örn. gövdede bir görsel olması veya birkaç paragraf olması çok uzatacaktır. Burada `strip_tags` ile html tagları temizlenip `truncate` ile görüntülenen metin sınırlandırılmalı.

i.e.
```ruby
=truncate(strip_tags(description), length: 150)
```

**Comment by ileri** [comment]
> Bence burada biçimlendirilmiş şekli görünümde problemler oluşturabilir. Örn. gövdede bir görsel olması veya birkaç paragraf olması çok uzatacaktır. Burada `strip_tags` ile html tagları temizlenip `truncate` ile görüntülenen metin sınırlandırılmalı.
> 
> i.e.
> 
> ```ruby
> =truncate(strip_tags(description), length: 150)
> ```

Uygulandı, commitlendi, canlıya alındı. :+1:
